### PR TITLE
readme fix

### PR DESCRIPTION
**Pull request by MrSerge01**
- centered the badges
- updated the inv link

### CODE REVIEW

**Comment by Froxcey** [comment]
> When the enemy is relaxed, make them toil. When full, starve them. When settled, make them move.

\- Sun Tsu, The Art of War

vibe

**Review by Froxcey — APPROVED** [review]
Besides the fact that your commits are not signed, LGTM!

vibe

**Comment by MrSerge01** [comment]
huh what thehell...

**Comment by LeOptix** [comment]
not centered 👍

**Review by ThatFrogDev — APPROVED** [review]
LGTM!

--Frog

**Pull request merged**
