### PR TITLE
changes were made

### PR DESCRIPTION
**Pull request by ThatFrogDev**
smh

### CODE REVIEW

**Review by ThatFrogDev — COMMENTED** [review]
noooooooooooo i cant accept my own pr @MrSerge01 please merge it

**Comment by MrSerge01** [comment]
why did you decide to do this

**Comment by MrSerge01** [comment]
> noooooooooooo i cant accept my own pr @MrSerge01 please merge it

was supposed to be mine but ok

**Review by MrSerge01 — APPROVED** [review]
My PR, my accepting.
LGTM,
-The Goos.

**Comment by ThatFrogDev** [comment]
> why did you decide to do this

because some helpful changes are in there

**Comment by ThatFrogDev** [comment]
> > noooooooooooo i cant accept my own pr @MrSerge01 please merge it
> 
> was supposed to be mine but ok

U right lmao

**Pull request merged**
